version: '3.8'

services:
  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: resume_analyzer_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_TYPE=firebase
      - FIREBASE_PROJECT_ID=resume-analyzer-platform
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-service-account.json
      - SECRET_KEY=Nfr1uhFFMnzmv7BagUUrITWl5D9vEWMS4A2QSzsApwU
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
    networks:
      - resume_analyzer_network
    command: ./start.sh

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: resume_analyzer_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - resume_analyzer_network
    command: npm start

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: resume_analyzer_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - resume_analyzer_network

networks:
  resume_analyzer_network:
    driver: bridge
